export const IMAGES = {
    BackImage: require("./BackImage.png"),
    MainLogo: require("./MainLogo.png"),
    BackArrow: require("./BackArrow.png"),
    Add: require("./Add.png"),
    Bell: require("./Bell.png"),
    Follow: require("./Follow.png"),
    Home: require("./Home.png"),
    Profile: require("./Profile.png"),
    AddStory: require("./AddStory.png"),
    BellWhite: require("./BellWhite.png"),
    Comments: require("./Comments.png"),
    DisLike: require("./DisLike.png"),
    Like: require("./Like.png"),
    SearchIcon: require("./SearchIcon.png"),
    UploadedImage: require("./UploadedImage.png"),
    ProfileImage:require("./ProfileImage.png"),
    CoverPhoto:require("./CoverPhoto.png"),
    PostOne:require("./PostOne.png"),
    PostTwo:require("./PostTwo.png"),
    // :require("."),
    // :require("."),
    // :require("."),
    // :require("."),
    // :require("."),

}